// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7zaxVorbdLgYHGhNNOK-Hr5HFXY2rJyM',
    appId: '1:233421571817:web:0a3d747842a6c5c8a59278',
    messagingSenderId: '233421571817',
    projectId: 'study-buddy-auth-2026-26e1b',
    authDomain: 'study-buddy-auth-2026-26e1b.firebaseapp.com',
    storageBucket: 'study-buddy-auth-2026-26e1b.firebasestorage.app',
    measurementId: 'G-D6NJB2YB3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHiJBs_yY2t_mW4IX516giwJpdH8v7ObI',
    appId: '1:233421571817:android:e080e954044b5646a59278',
    messagingSenderId: '233421571817',
    projectId: 'study-buddy-auth-2026-26e1b',
    storageBucket: 'study-buddy-auth-2026-26e1b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpR8xRnSsENuVNz51I8hDLgYRG6ojfSP8',
    appId: '1:233421571817:ios:eff9f2a002b84d0aa59278',
    messagingSenderId: '233421571817',
    projectId: 'study-buddy-auth-2026-26e1b',
    storageBucket: 'study-buddy-auth-2026-26e1b.firebasestorage.app',
    iosBundleId: 'com.example.studyBuddyFirebase',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpR8xRnSsENuVNz51I8hDLgYRG6ojfSP8',
    appId: '1:233421571817:ios:eff9f2a002b84d0aa59278',
    messagingSenderId: '233421571817',
    projectId: 'study-buddy-auth-2026-26e1b',
    storageBucket: 'study-buddy-auth-2026-26e1b.firebasestorage.app',
    iosBundleId: 'com.example.studyBuddyFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7zaxVorbdLgYHGhNNOK-Hr5HFXY2rJyM',
    appId: '1:233421571817:web:01668a93acf8f36ea59278',
    messagingSenderId: '233421571817',
    projectId: 'study-buddy-auth-2026-26e1b',
    authDomain: 'study-buddy-auth-2026-26e1b.firebaseapp.com',
    storageBucket: 'study-buddy-auth-2026-26e1b.firebasestorage.app',
    measurementId: 'G-EPNZ5SYLXL',
  );
}
